package com.cw2.cw_1kito.error

/**
 * OCR 错误码
 */
enum class OcrErrorCode(val code: String, val message: String) {
    OCR_INIT_FAILED("OCR_INIT_FAILED", "OCR 模型初始化失败"),
    OCR_RUNTIME_ERROR("OCR_RUNTIME_ERROR", "OCR 推理运行时错误"),
    OCR_INVALID_IMAGE("OCR_INVALID_IMAGE", "无效图像输入"),
    OCR_MODEL_NOT_LOADED("OCR_MODEL_NOT_LOADED", "模型未加载"),
    OCR_ENGINE_UNAVAILABLE("OCR_ENGINE_UNAVAILABLE", "OCR 引擎不可用")
}

/**
 * 翻译错误码
 */
enum class TranslationErrorCode(val code: String, val message: String) {
    TRANSLATION_INIT_FAILED("TRANSLATION_INIT_FAILED", "翻译引擎初始化失败"),
    TRANSLATION_LOCAL_FAILED("TRANSLATION_LOCAL_FAILED", "本地翻译失败"),
    TRANSLATION_REMOTE_FAILED("TRANSLATION_REMOTE_FAILED", "远程翻译失败"),
    TRANSLATION_TIMEOUT("TRANSLATION_TIMEOUT", "翻译超时"),
    TRANSLATION_API_KEY_INVALID("TRANSLATION_API_KEY_INVALID", "API Key 无效"),
    TRANSLATION_RATE_LIMIT_EXCEEDED("TRANSLATION_RATE_LIMIT_EXCEEDED", "API 配额超限"),
    TRANSLATION_NETWORK_ERROR("TRANSLATION_NETWORK_ERROR", "网络错误"),
    TRANSLATION_UNSUPPORTED_LANGUAGE("TRANSLATION_UNSUPPORTED_LANGUAGE", "不支持的语言对"),
    TRANSLATION_INVALID_RESPONSE("TRANSLATION_INVALID_RESPONSE", "API 响应无效"),
    TRANSLATION_MODEL_NOT_AVAILABLE("TRANSLATION_MODEL_NOT_AVAILABLE", "翻译模型不可用")
}

/**
 * 系统错误码
 */
enum class SystemErrorCode(val code: String, val message: String) {
    PERMISSION_DENIED("PERMISSION_DENIED", "权限被拒绝"),
    PERMISSION_EXPIRED("PERMISSION_EXPIRED", "权限已过期"),
    STORAGE_INSUFFICIENT("STORAGE_INSUFFICIENT", "存储空间不足"),
    OUT_OF_MEMORY("OUT_OF_MEMORY", "内存不足"),
    UNKNOWN_ERROR("UNKNOWN_ERROR", "未知错误"),
    SCREEN_CAPTURE_FAILED("SCREEN_CAPTURE_FAILED", "屏幕截图失败"),
    SERVICE_NOT_RUNNING("SERVICE_NOT_RUNNING", "服务未运行"),
    CONFIGURATION_INVALID("CONFIGURATION_INVALID", "配置无效")
}
